name: example
description: example of functional data

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  functional_data:

dev_dependencies:
  build_runner: ^1.10.0
  build_resolvers: ">=1.3.10"
  functional_data_generator:
    path: ../functional_data_generator