name: functional_data_generator
version: 1.0.0-nullsafety.2
description: >-
  Simple and non-intrusive code generator for boilerplate of data types.
homepage: https://github.com/spkersten/dart_functional_data

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  analyzer: ^0.40.6
  build: ^1.5.0
  source_gen: ^0.9.6
  collection: ^1.15.0-nullsafety.5
  functional_data: ^1.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.10.0
  build_resolvers: ">=1.4.0"
