name: PR validation
on: [pull_request]
jobs:
  test_line_length:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: functional_data
      - run: flutter pub get
        working-directory: functional_data_generator
      - run: flutter pub get
        working-directory: example
      - run: dart format -o none -l 120 --set-exit-if-changed .
